version: '3'
services:
  discord-bot:
    build: ./black-jack-bot/.
    env_file:
      - ./black-jack-bot/.env
    depends_on:
      - redis

  redis:
    image: redis
    command: ["redis-server", "--save", "10", "1"]
    volumes:
      - ./data:/data