# Use the official Python image as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Set the environment variable for the Discord token
ENV DISCORD_TOKEN=MTIyNDg2MTQ1ODY4OTU2MDYzNw.Gx89nZ.zMW3q8BDOpnTHfx4xacIiyqRYiBuFrwAs_kEkI

# Run the application
CMD ["python", "main.py"]