version: '3'
services:
  discord-bot:
    build: .
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis
    command: ["redis-server", "--save", "10", "1"]
    volumes:
      - ./data:/data