version: '3'
services:
  discord-bot:
    build: .
    environment:
      - DISCORD_TOKEN=<Your Token>
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis